name: CI Pipeline Statique

on:
  push:
    branches: [feature_docker]
  pull_request:
    branches: [feature_docker]

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier la syntaxe HTML
        run: npx htmlhint "**/*.html"

      - name: Tester la construction Docker
        run: docker build -t new_atelier_botanique:4.0 .
