name: CI Pipeline Statique

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier la syntaxe HTML
        run: npx htmlhint "**/*.html"

      - name: Tester la construction Docker
        run: docker build -t mon-image-test .
